# Modern Nutrition Solutions BI Configuration
name = "nutrition-solutions-bi"
main = "src/index.ts"
compatibility_date = "2024-08-01"

# Environment variables
[vars]
KEAP_CLIENT_ID = "q97htu3Rn9eW0tSPh5WNIWeN5bUVn57sIWiAZctwx3O8kov6"
KEAP_APP_ID = "f3758888-5b87-4228-b394-669991d857f8"

# D1 Database binding - using your nutrition-solutions-db
[[d1_databases]]
binding = "DB"
database_name = "nutrition-solutions-db"
database_id = "d6966e03-8afe-4fae-b150-474104552cdb"

# KV namespace for sync state
[[kv_namespaces]]
binding = "SYNC_STATE"
id = "e3c00f1508eb40839e312defdbc0b696"
preview_id = "c494a513826048dfb8c4d50fce4f6242"

[[kv_namespaces]]
binding = "CACHE"
id = "your-cache-namespace-id"
preview_id = "your-cache-preview-id"

# R2 bucket for file storage and exports
[[r2_buckets]]
binding = "REPORTS"
bucket_name = "nutrition-bi-reports"

# Queue for background processing
[[queues.producers]]
binding = "SYNC_QUEUE"
queue = "nutrition-data-sync"

# Analytics Engine for performance monitoring
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "nutrition_bi_metrics"

# Observability settings
[observability.logs]
enabled = true

# Scheduled triggers for automatic sync (every 6 hours)
[triggers]
crons = ["0 */6 * * *"]