#!/bin/bash

echo "🔧 Hyperdrive Local Development Setup"
echo "====================================="
echo ""
echo "To use Hyperdrive locally, you need a PostgreSQL connection string."
echo ""
echo "Your Supabase project URL is: https://ulyrnuemxucoglbcwzig.supabase.co"
echo ""
echo "To get your connection string:"
echo "1. Go to https://supabase.com/dashboard/project/ulyrnuemxucoglbcwzig/settings/database"
echo "2. Find the 'Connection string' section"
echo "3. Copy the 'URI' connection string"
echo "4. It should look like:"
echo "   postgresql://postgres.ulyrnuemxucoglbcwzig:[YOUR-PASSWORD]@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
echo ""
echo "Then run these commands:"
echo ""
echo "# Create .env file from example"
echo "cp .env.example .env"
echo ""
echo "# Edit .env and add your connection string"
echo "# Replace [YOUR-SUPABASE-PASSWORD] with your actual password"
echo "nano .env"
echo ""
echo "# Or set it directly (replace with your actual connection string):"
echo 'export WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE="postgresql://postgres.ulyrnuemxucoglbcwzig:[YOUR-PASSWORD]@aws-0-us-east-1.pooler.supabase.com:5432/postgres"'
echo ""
echo "# Then run the development server:"
echo "./dev.sh"
echo ""
echo "Alternative: Install PostgreSQL locally"
echo "======================================="
echo "brew install postgresql@16"
echo "brew services start postgresql@16"
echo "createdb hyperdrive_dev"
echo 'export WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE="postgresql://localhost:5432/hyperdrive_dev"'